# Generated by Django 5.0 on 2026-02-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekerprofile_bio_jobseekerprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Education details'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='A short professional headline', max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_resume_public',
            field=models.BooleanField(default=True, help_text='Allow recruiters to see your resume'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Work experience details'),
        ),
    ]
