# Generated by Django 5.0 on 2026-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekerprofile_education_jobseekerprofile_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Current city/region', max_length=255),
        ),
    ]
