# Generated by Django 5.0 on 2026-02-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobseekerprofile_location'),
        ('accounts', '0005_jobseekerprofile_profile_photo'),
    ]

    operations = [
    ]
