# Generated by Django 5.0 on 2026-02-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260217_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='profile_photo',
        ),
    ]
