# Generated by Django 5.0 on 2026-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_screeningquestion_applicationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=500),
        ),
    ]
