# Generated by Django 5.0 on 2026-02-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='Does this job offer visa sponsorship?'),
        ),
    ]
