# Generated by Django 5.0 on 2026-02-19 00:00

from django.db import migrations, models


def auto_approve_existing_active_jobs(apps, schema_editor):
    Job = apps.get_model("jobboard", "Job")
    Job.objects.filter(is_active=True, is_approved=False).update(is_approved=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jobboard", "0008_job_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(auto_approve_existing_active_jobs, noop_reverse),
    ]
